kern.uv_bins_du = 20
kern.uv_bins_n_uni = 8


kern.fg = ['fg_int', 'fg_mix']
kern.eor = ['eor_vae', 'eor_excess']

gp.use_uv_weight = true

# sampler_method = 'mcmc' 
# mcmc.n_steps = 200
# mcmc.n_walkers = 200
# mcmc.n_burn = 100

sampler_method = 'ultranest'
ultranest.nlive = 100




#mcmc.move = 'kde'


[fg_int]
type = 'MRBF'
# variance.prior = 'Log10Uniform(-0., 0.5)'
# variance.prior = 'Log10Uniform(-0.5, 0.5)'
variance.prior = 'Log10Uniform(-0.7, -0.1)'

variance.log_scale = true
# we fixed the lenghtscale
lengthscale.prior = 'Fixed(80)'
ls_alpha.prior = 'Fixed(0)'
use_uv_ps = true

[fg_mix]
type = 'MMat32'
wedge_parametrization = true
# variance.prior = 'Log10Uniform(-0.8, -0.01)'
variance.prior = 'Log10Uniform(-0.5, -0.1)'
variance.log_scale = true
# theta_rad.prior = 'Uniform(0.01, 1.6)'
theta_rad.prior = 'Uniform(0.01, 0.4)'
delay_buffer_us.prior = 'Fixed(0.1)'
lengthscale.prior = 'Fixed(1)'

[eor_vae]
type = 'VAEKernTorch'
fitter_filename = '/home/codex/chege/ml_gpr_models/vae_z9.164_n1500_GRIZZLY_latent2.pt'
x1.prior = 'Uniform(-3, 3)'
x2.prior = 'Uniform(-3, 3)'
variance.prior = 'Log10Uniform(-7, -0.5)'
variance.log_scale = true


[eor_excess]
type = 'MMat52'
variance.prior = 'Log10Uniform(-3.5, -1.5)'
variance.log_scale = true
# lengthscale.prior = 'Uniform(0.2, 0.8)'
lengthscale.prior = 'Uniform(0.01, 0.4)'
# ls_alpha.prior = 'Uniform(-5, 60)'
ls_alpha.prior = 'Uniform(10, 120)'
# var_alpha.prior = 'Fixed(-0.25)'
var_alpha.prior = 'Uniform(-0.5, 1.5)'


[kern.noise]
alpha.prior = 'Uniform(0.5, 1.5)' #'Fixed(1)'
use_simulated_noise_cube = false
use_sefd_freqs_estimate = true
use_noise_std = false
estimate_baseline_noise_from_stokes = 'V'
estimate_baseline_noise_remove_n_pca = 0
estimate_baseline_noise_from_channel_diff = false
scale_baseline_noise = false
